- name : install mysql
  ansible.builtin.dnf:
       name : mysql-server
       state : present

- name: enable and start mysql
  ansible.builtin.service:
        name : mysqld
        state : restarted
        enabled: yes

- name : setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1