- name : enable nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name : install nodejs
  ansible.builtin.dnf:
       name : nodejs
       state : present

- name : download dependencies
  community.general.npm:
        path: /app
        
